# Bu dosya ile Nginx'e gelen PHP isteklerini WordPress konteynerinin 9000 portuna yönlendirmesini söyleyeceğiz.

events{}

http {
    include /etc/nginx/mime.types;

    server {
        # Sadece 443 portunu SSL ile dinle
        listen 443 ssl;
        server_name iekmen.42.fr;

        # TLSv1.2 veya TLSv1.3 zorunluluğu
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_certificate /etc/nginx/ssl/inception.crt;
        ssl_certificate_key /etc/nginx/ssl/inception.key;

        root /var/www/wordpress;
        index index.php index.html;

        # PHP dosyalarını WordPress konteynerine (9000 portu) yönlendir
        location ~ \.php$ {
            include snippets/fastcgi-php.conf;
            fastcgi_pass wordpress:9000;
        }
    }
}