version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception_network

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    restart: always
    env_file: .env
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception_network
    depends_on:
      - mariadb

  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception_network
    depends_on:
      - wordpress

# LÜTFEN DİKKAT: Aşağıdaki iki satır en sola yaslı olmalı (önlerinde hiç boşluk yok)
volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/iekmen/data/wordpress
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/iekmen/data/mariadb

networks:
  inception_network:
    driver: bridge
    name: inception_network